require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AddFieldsToRisksController do

  # This should return the minimal set of attributes required to create a valid
  # AddFieldsToRisk. As you add validations to AddFieldsToRisk, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AddFieldsToRisksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all add_fields_to_risks as @add_fields_to_risks" do
      add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
      get :index, {}, valid_session
      assigns(:add_fields_to_risks).should eq([add_fields_to_risk])
    end
  end

  describe "GET show" do
    it "assigns the requested add_fields_to_risk as @add_fields_to_risk" do
      add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
      get :show, {:id => add_fields_to_risk.to_param}, valid_session
      assigns(:add_fields_to_risk).should eq(add_fields_to_risk)
    end
  end

  describe "GET new" do
    it "assigns a new add_fields_to_risk as @add_fields_to_risk" do
      get :new, {}, valid_session
      assigns(:add_fields_to_risk).should be_a_new(AddFieldsToRisk)
    end
  end

  describe "GET edit" do
    it "assigns the requested add_fields_to_risk as @add_fields_to_risk" do
      add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
      get :edit, {:id => add_fields_to_risk.to_param}, valid_session
      assigns(:add_fields_to_risk).should eq(add_fields_to_risk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AddFieldsToRisk" do
        expect {
          post :create, {:add_fields_to_risk => valid_attributes}, valid_session
        }.to change(AddFieldsToRisk, :count).by(1)
      end

      it "assigns a newly created add_fields_to_risk as @add_fields_to_risk" do
        post :create, {:add_fields_to_risk => valid_attributes}, valid_session
        assigns(:add_fields_to_risk).should be_a(AddFieldsToRisk)
        assigns(:add_fields_to_risk).should be_persisted
      end

      it "redirects to the created add_fields_to_risk" do
        post :create, {:add_fields_to_risk => valid_attributes}, valid_session
        response.should redirect_to(AddFieldsToRisk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved add_fields_to_risk as @add_fields_to_risk" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddFieldsToRisk.any_instance.stub(:save).and_return(false)
        post :create, {:add_fields_to_risk => {}}, valid_session
        assigns(:add_fields_to_risk).should be_a_new(AddFieldsToRisk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddFieldsToRisk.any_instance.stub(:save).and_return(false)
        post :create, {:add_fields_to_risk => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested add_fields_to_risk" do
        add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
        # Assuming there are no other add_fields_to_risks in the database, this
        # specifies that the AddFieldsToRisk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AddFieldsToRisk.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => add_fields_to_risk.to_param, :add_fields_to_risk => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested add_fields_to_risk as @add_fields_to_risk" do
        add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
        put :update, {:id => add_fields_to_risk.to_param, :add_fields_to_risk => valid_attributes}, valid_session
        assigns(:add_fields_to_risk).should eq(add_fields_to_risk)
      end

      it "redirects to the add_fields_to_risk" do
        add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
        put :update, {:id => add_fields_to_risk.to_param, :add_fields_to_risk => valid_attributes}, valid_session
        response.should redirect_to(add_fields_to_risk)
      end
    end

    describe "with invalid params" do
      it "assigns the add_fields_to_risk as @add_fields_to_risk" do
        add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddFieldsToRisk.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_fields_to_risk.to_param, :add_fields_to_risk => {}}, valid_session
        assigns(:add_fields_to_risk).should eq(add_fields_to_risk)
      end

      it "re-renders the 'edit' template" do
        add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddFieldsToRisk.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_fields_to_risk.to_param, :add_fields_to_risk => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested add_fields_to_risk" do
      add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
      expect {
        delete :destroy, {:id => add_fields_to_risk.to_param}, valid_session
      }.to change(AddFieldsToRisk, :count).by(-1)
    end

    it "redirects to the add_fields_to_risks list" do
      add_fields_to_risk = AddFieldsToRisk.create! valid_attributes
      delete :destroy, {:id => add_fields_to_risk.to_param}, valid_session
      response.should redirect_to(add_fields_to_risks_url)
    end
  end

end
